{
 "title": "Benchmarks",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "peer",
    "query": {
     "query": "label_values(topos_certificate_received_total,job)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Certificate created",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(topos_certificate_received_total{job=~\"$peer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificate delivered",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topos_certificate_delivered_total{job=~\"$peer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full Delivery",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "targets": [
    { "expression": "100 * ($B ) / ($A * 15) ", "type": "math" }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (irate(topos_certificate_delivered_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by(le) (increase(topos_p2p_gossip_batch_size_bucket[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Delivery dynamic",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (increase(topos_certificate_delivered_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(topos_double_echo_delivery_latency_sum[$__rate_interval]) / rate(topos_double_echo_delivery_latency_count[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(topos_double_echo_delivery_latency_sum[$__rate_interval]) / rate(topos_double_echo_delivery_latency_count[$__rate_interval]))",
     "legendFormat": "min"
    },
    {
     "expr": "max(rate(topos_double_echo_delivery_latency_sum[$__rate_interval]) / rate(topos_double_echo_delivery_latency_count[$__rate_interval]))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Certificate reception",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "topos_certificate_received_from_gossip_total{job=~\"$peer\"}",
     "legendFormat": "Gossip {{job}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Gossip received vs. Echo published",
   "type": "timeseries",
   "description": "Latency between rounds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(hash) (increase(topos_libp2p_gossipsub_topic_msg_recv_counts_total{hash=\"topos_gossip\", job=~\"$peer\"}[$__rate_interval]))",
     "legendFormat": "Gossip received"
    },
    {
     "expr": "sum by(hash) (increase(topos_libp2p_gossipsub_topic_msg_published_total{hash=\"topos_echo\", job=~\"$peer\"}[$__rate_interval]))",
     "legendFormat": "Echo published"
    },
    {
     "expr": "sum by(hash) (increase(topos_libp2p_gossipsub_topic_iwant_msgs_total{hash=\"topos_gossip\", job=~\"$peer\"}[$__rate_interval]))",
     "legendFormat": "IWANT Gossip"
    }
   ]
  },
  {
   "title": "Ratio payload recv unfiltered vs. filtered",
   "type": "timeseries",
   "description": "Measure the redundancy",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by(instance) (avg by(hash) (topos_libp2p_gossipsub_topic_msg_recv_counts_total{job=~\"$peer\"}))",
     "legendFormat": "Filtered"
    },
    {
     "expr": "sum by(instance) (avg by(hash) (topos_libp2p_gossipsub_topic_msg_recv_counts_unfiltered_total{job=~\"$peer\"}))",
     "legendFormat": "Unfiltered"
    },
    { "expression": "$unfiltered / $filtered", "type": "math" }
   ]
  },
  {
   "title": "Echo received vs. Ready published",
   "type": "timeseries",
   "description": "Latency between rounds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(hash) (increase(topos_libp2p_gossipsub_topic_msg_recv_counts_total{hash=\"topos_echo\", job=~\"$peer\"}[$__rate_interval]))",
     "legendFormat": "Echo received"
    },
    {
     "expr": "sum by(hash) (increase(topos_libp2p_gossipsub_topic_msg_published_total{hash=\"topos_ready\", job=~\"$peer\"}[$__rate_interval]))",
     "legendFormat": "Ready published"
    },
    {
     "expr": "sum by(hash) (increase(topos_libp2p_gossipsub_topic_iwant_msgs_total{hash=\"topos_echo\", job=~\"$peer\"}[$__rate_interval]))",
     "legendFormat": "IWANT Echo"
    }
   ]
  },
  {
   "title": "Certificate delivered per peer",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topos_certificate_delivered_total{job=~\"$peer\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Ready received vs. Ready published vs. Delivered certificate",
   "type": "timeseries",
   "description": "Latency between rounds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by(hash) (increase(topos_libp2p_gossipsub_topic_msg_recv_counts_total{hash=\"topos_ready\", job=~\"$peer\"}[$__rate_interval]))",
     "legendFormat": "Ready received"
    },
    {
     "expr": "sum by(hash) (increase(topos_libp2p_gossipsub_topic_msg_published_total{hash=\"topos_ready\", job=~\"$peer\"}[$__rate_interval]))",
     "legendFormat": "Ready published"
    },
    {
     "expr": "sum by(hash) (increase(topos_libp2p_gossipsub_topic_iwant_msgs_total{hash=\"topos_ready\", job=~\"$peer\"}[$__rate_interval]))",
     "legendFormat": "IWANT Ready"
    },
    { "expression": "$total_cert - $cert_delivered", "type": "math" }
   ]
  },
  { "title": "P2P - Gossip protocol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "IWANT msg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "irate(topos_libp2p_gossipsub_topic_iwant_msgs_total{ job=~\"$peer\"}[$__interval])",
     "legendFormat": "IWANT {{hash}} - {{job}}"
    }
   ]
  },
  {
   "title": "MSG recv filtered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "irate(topos_libp2p_gossipsub_topic_msg_recv_counts_total{ job=~\"$peer\"}[$__interval])",
     "legendFormat": "{{hash}} {{job}}"
    }
   ]
  },
  {
   "title": "MSG recv total per topic",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(hash) (topos_libp2p_gossipsub_topic_msg_recv_counts_total{ job=~\"$peer\"})",
     "legendFormat": "{{hash}} "
    }
   ]
  },
  {
   "title": "MSG sent total per topic",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "max by(hash, job) (topos_libp2p_gossipsub_topic_msg_sent_counts_total{ job=~\"$peer\"})",
     "legendFormat": "{{job}} {{hash}}"
    }
   ]
  },
  { "title": "Storage layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Command channel at capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "irate(topos_storage_command_channel_capacity_total{ job=~\"$peer\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pending existance latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(topos_storage_pending_certificate_existance_latency_bucket{ job=~\"$peer\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Adding to pending latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(topos_storage_adding_pending_certificate_latency_bucket{ job=~\"$peer\"}[$__range])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "P2P layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "P2P Channel at capacity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "irate(topos_p2p_event_stream_capacity_total{ job=~\"$peer\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Message received",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "irate(topos_p2p_echo_message_total{ job=~\"$peer\"}[$__interval])",
     "legendFormat": "Echo {{job}}"
    },
    {
     "expr": "irate(topos_p2p_ready_message_total{ job=~\"$peer\"}[$__interval])",
     "legendFormat": "Ready {{job}}"
    },
    {
     "expr": "irate(topos_p2p_gossip_message_total{ job=~\"$peer\"}[$__interval])",
     "legendFormat": "Gossip {{job}}"
    }
   ]
  },
  {
   "title": "Gossip message sent",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "sum(topos_p2p_gossipsub_message_sent_total{ job=~\"$peer\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Gossip message sent",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(topos_p2p_gossip_batch_size_bucket{ job=~\"$peer\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Double Echo - external", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Command channel capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "irate(topos_double_echo_command_channel_capacity_total{ job=~\"$peer\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Double Echo - internal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Double echo - Buffer size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "topos_double_echo_current_buffer_size{ job=~\"$peer\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Double Echo Buffer at capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "irate(topos_double_echo_buffer_capacity_total{ job=~\"$peer\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Double echo - Buffered messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "topos_double_echo_buffered_message_count{ job=~\"$peer\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Double echo - Buffer size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "expr": "topos_double_echo_current_buffer_size{ job=~\"$peer\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}