name: Audit

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  audit:
    strategy:
      fail-fast: false
      matrix:
        version: [stable]
    name: ${{ matrix.version }} - Audit
    uses: toposware/topos/.github/workflows/docker_utils.yml@main
    secrets: inherit
    with:
      target: audit
      toolchain_version: ${{ matrix.version }}
