name: E2E tests on Kubernetes

on:
  schedule:
    # Triggers the workflow every day at 5:30 UTC:
    - cron:  '30 5 * * *'
  push:
    # Triggers on merge into main
    branches: [main, test/clean-up-ci]

jobs:
  docker:
    uses: toposware/topos/.github/workflows/docker_utils.yml@test/clean-up-ci
    secrets: inherit
  k8s:
    # run only when the workflow was scheduled or a PR is being merged into main
    if: ${{ (github.event_name == 'push') || (github.event_name == 'schedule') }}
    needs: docker
    uses: toposware/topos/.github/workflows/k8s_utils.yml@test/clean-up-ci
    secrets: inherit
