name: E2E tests on Kubernetes

on:
  schedule:
    # Triggers the workflow every day at 5:30 UTC:
    - cron:  '30 5 * * *'
  push:
    # Triggers on merge into main
    branches: [main, test/k8s-e2e]

jobs:
  docker:
    uses: toposware/topos/.github/workflows/docker_utils.yml@test/k8s-e2e
    secrets: inherit
  k8s:
    needs: docker
    uses: toposware/topos/.github/workflows/k8s_utils.yml@test/k8s-e2e
    secrets: inherit
