name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        version: [stable]
    name: ${{ matrix.version }} - Lint
    uses: toposware/topos/.github/workflows/docker_utils.yml@main
    secrets: inherit
    with:
      target: lint
      toolchain_version: ${{ matrix.version }}
