name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    container: paritytech/ci-linux:production
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: RUSTFLAGS='-D warnings' cargo build --verbose
      - name: Test
        run: cargo test --all --verbose
  clippy:
    name: Lint and Format
    runs-on: ubuntu-latest
    container: paritytech/ci-linux:production
    steps:
      - uses: actions/checkout@v2
      - name: Clippy
        run: cargo clippy --all -- -D clippy::suspicious
      - name: Fmt
        run: cargo fmt --all --check
